# Generated by Django 5.1 on 2024-08-30 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionalStatement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fgid', models.CharField(max_length=10)),
                ('directional_statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fgid', models.CharField(max_length=10)),
                ('fgcat_id', models.CharField(max_length=10, unique=True)),
                ('fgcat', models.CharField(max_length=255)),
                ('foodgroup', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServingPerDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fgid', models.CharField(max_length=10)),
                ('gender', models.CharField(default='Unknown', max_length=10)),
                ('ages', models.CharField(default='Unknown', max_length=50)),
                ('servings', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fgid', models.CharField(max_length=10)),
                ('srvg_sz', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=255)),
                ('fgcat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.foodgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_data', models.JSONField()),
                ('selected', models.BooleanField(default=False)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
